version: '3'

services:
  app:
    image: jamshidbekmansurov/denta-plus:latest
    container_name: denta_plus_app
    restart: always
    ports:
      - '4001:4001'
    env_file:
      - .env
    depends_on:
      denta_plus_postgres:
        condition: service_healthy
      denta_plus_redis:
        condition: service_healthy
    networks:
      - denta_plus_network

  denta_plus_postgres:
    image: postgres:16-alpine
    container_name: denta_plus_postgres
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - denta_plus_postgres_data:/var/lib/postgresql/data
    networks:
      - denta_plus_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  denta_plus_redis:
    image: redis:7.2-alpine
    container_name: denta_plus_redis
    ports:
      - '6381:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - denta_plus_redis_data:/data
    networks:
      - denta_plus_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  denta_plus_postgres_data:
  denta_plus_redis_data:

networks:
  denta_plus_network:
    driver: bridge