version: '3'
services:
  app:
    image: jamshidbekmansurov/denta-plus:latest
    container_name: denta-plus
    restart: always
    ports:
      - '4001:4000'
    env_file:
      - .env
    networks:
      - existing-network

networks:
  existing-network:
    external: true