version: '3'

services:
  app:
    image: jamshidbekmansurov/smart-start:latest
    container_name: denta-plus
    restart: always
    ports:
      - '4001:4000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - common-network

networks:
  common-network:
    external: true