version: '3'

services:
  app:
    image: jamshidbekmansurov/denta-plus:latest
    container_name: denta_plus
    restart: always
    ports:
      - '4001:4000'
    env_file:
      - .env
    networks:
      - common-network

networks:
  common-network:
    external: true
