version: '3'

services:
  app:
    image: ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest
    container_name: denta-plus
    restart: always
    ports:
      - '4001:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - existing-network

networks:
  existing-network:
    external: true
