name: Deploy Denta-Plus to Ubuntu Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/denta-plus:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/denta-plus:buildcache,mode=max

      - name: Deploy to Ubuntu Server
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY }}
    script: |
      # Network yaratish (agar mavjud bo'lmasa)
      docker network create existing-network || true

      # Qolgan deploy skripti o'zgarmaydi
      cd ~/denta-plus || mkdir -p ~/denta-plus && cd ~/denta-plus

      # Docker Compose faylini yaratish
      cat > docker-compose.yml << EOL
      version: '3'
      services:
        app:
          image: ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest
          container_name: denta-plus
          restart: always
          ports:
            - '4001:4000'
          env_file:
            - .env
          networks:
            - existing-network

      networks:
        existing-network:
          external: true
      EOL

            # Eski konteynerlarni to'xtatish
            docker-compose down

            # .env faylini yangilash
            printf "%s" "${{ secrets.ENV_FILE }}" > .env

            # Eng so'nggi Docker imagelarini olish
            docker pull ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest

            # Konteynerlarni ishga tushirish
            docker-compose up -d --remove-orphans

            # Diskda bo'sh joy ochish
            docker image prune -a -f --filter "until=24h"

            # Servislar holatini tekshirish
            sleep 15
            docker ps
            docker logs --tail=30 denta-plus
