name: Deploy Denta-Plus to Ubuntu Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/denta-plus:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/denta-plus:buildcache,mode=max
      
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Application directory
            mkdir -p ~/denta-plus
            cd ~/denta-plus
            
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest
            
            # Stop and remove current container if exists
            if [ -f docker-compose.yml ]; then
              docker-compose down
            fi
            
            # Create .env file from GitHub secret
            printf "%s" "${{ secrets.ENV_FILE }}" > .env
            
            # Create or update docker-compose.yml
            cat > docker-compose.yml << 'EOL'
            version: '3'

            services:
              app:
                image: ${{ secrets.DOCKER_USERNAME }}/denta-plus:latest
                container_name: denta-plus
                restart: always
                ports:
                  - '4001:3000'
                env_file:
                  - .env
                depends_on:
                  - postgres
                  - redis
                networks:
                  - existing-network

            networks:
              existing-network:
                external: true
            EOL
            
            # Start the application
            docker-compose up -d --remove-orphans
            
            # Prune unused images to save disk space
            docker image prune -a -f --filter "until=24h"
            
            # Check if application started successfully
            sleep 15
            docker ps --filter "name=denta-plus"
            docker logs --tail=30 -f denta-plus
